# Utilisez l'image officielle Apache
FROM httpd:latest

# Copiez les fichiers de votre projet dans le conteneur
COPY . /usr/local/apache2/htdocs/

# Exposez le port 80 pour permettre l'accès au serveur web
EXPOSE 80
