name: test Ionic(jest)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: testing ionic
      run: |
        npm i @ionic/react-test-utils
        npm run test.unit
    - name : build 
      run : | 
        npm install -g @ionic/cli
        ionic build
    - name : deploy
      run : curl -X POST -d {} https://api.netlify.com/build_hooks/65c62f05f6e8290fa49193c7