name: test Ionic(jest)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: testing ionic
      run: |
        npm i @ionic/react-test-utils
        npm run test.unit
    - name : build ionic
      run : |
        npm install -g @ionic/cli
        ionic build