name: Test Ionic (jest) and Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Install dependencies and run Ionic tests
      run: |
        cd frontend
        npm install
        npm i @ionic/react-test-utils
        npm run test.unit
        cd ..

  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.KEY_SSH }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .ssh directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts

    - name: Update known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.KEY_SSH }}

    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} /bin/bash << EOF
          cd TFE2
          git pull

          cd frontend
          npm install
          npm i @ionic/react-test-utils
          npm run test.unit
          cd ..

          docker stop serveur_web || true
          docker rm serveur_web || true

          docker build -t mon_projet_web .
          docker run -d -p 8080:80 --name serveur_web mon_projet_web
          exit
        EOF
