name: Test Ionic (jest) and Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Install dependencies and run Ionic tests
      run: |
        cd frontend
        npm install
        npm i @ionic/react-test-utils
        npm run test.unit
        cd ..

  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.6
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh user@your-vps-ip << 'EOF'
          cd /path/to/TFE2
          git pull

          cd frontend
          npm install
          npm i @ionic/react-test-utils
          npm run test.unit
          cd ..

          docker stop serveur_web || true
          docker rm serveur_web || true

          docker build -t mon_projet_web .
          doc
